version: "{build}-{branch}"

# Source Config
clone_folder: C:\gopath\src\github.com\eris-ltd\eris

environment:
  global:
    TEST_ON_WINDOWS: "true"
    DOCKER_MACHINE: "true"
    GOPATH: C:\gopath
    GOBIN: C:\gopath\bin
    PATH: '%PATH%;C:\gopath\bin'
    MACHINE_NAME: 'eris-test-win-%APPVEYOR_BUILD_ID%'
    SKIP_STACK: "true" # remove later when stack tests work on windows.
    DOCKER_VERSION: 1.10.0
    DOCKER_MACHINE_VERSION: 0.4.1
    AWS_ACCESS_KEY_ID:
      secure: qHdpZ2qgqg7LcbD1GJJ5JHPZJ1Bn0dQ8LoXgZpKrXBQ=
    AWS_SECRET_ACCESS_KEY:
      secure: SM1ZHeoInEuFq7Crxwsvq+9ukaCpR4lFBoPGRMTUIOOPmzCwOU6nTqO+NFW1DnQO
    AWS_DEFAULT_REGION: eu-west-1
    AWS_VPC_ID:
      secure: Lo717dojMJUNytpQPZWwyw==
    AWS_SECURITY_GROUP:
      secure: Jie7WuAzjiHVp7tX8MfaSQ==

build_script:
- cmd: >-

    choco install -yr cygwin > nul

    choco install -yr jq

    choco install -yr docker -version %DOCKER_VERSION%

    choco install -yr docker-machine -version %DOCKER_MACHINE_VERSION%

    cd c:\src\github.com\eris-ltd\eris\cmd\eris

    go get

    go install

after_test:
  - bash c:\src\github.com\eris-ltd\eris\tests\dm_cleanup.sh

test_script:
- cmd: >-

    bash c:\src\github.com\eris-ltd\eris\tests\test.sh
